package ui.mypark.com;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.border.TitledBorder;
import javax.swing.tree.DefaultMutableTreeNode;

public class ParkMessage extends JPanel {
	private JButton p_zj = new JButton("增加");
	private JButton p_xg = new JButton("修改");
	private JButton p_sc = new JButton("删除");
	private JButton p_cc = new JButton("存储");
	private JButton p_fq = new JButton("放弃");
	private JButton c_zj = new JButton("增加");
	private JButton c_xg = new JButton("修改");
	private JButton c_sc = new JButton("删除");
	private JButton c_cc = new JButton("存储");
	private JButton c_fq = new JButton("放弃");
	private JButton w_zj = new JButton("增加");
	private JButton w_xg = new JButton("修改");
	private JButton w_sc = new JButton("删除");
	private JButton w_cc = new JButton("存储");
	private JButton w_fq = new JButton("放弃");
	private JTextField p_jf1 = new JTextField(3);
	private JTextField p_jf2 = new JTextField(12);
	private JTextField p_jf3 = new JTextField(5);
	private JTextField p_jf4 = new JTextField(5);
	private JCheckBox p_jcb1 = new JCheckBox("免费");
	private JComboBox p_jcb2 = new JComboBox();
	private JTextField p_jf5 = new JTextField(24);
	private JTextField c_jf1 = new JTextField(3);
	private JTextField c_jf2 = new JTextField(12);
	private JTextField c_jf3 = new JTextField(15);
	private JComboBox c_jcb_a1 = new JComboBox();
	private JComboBox c_jcb_a2 = new JComboBox();
	private JComboBox c_jcb_b1 = new JComboBox();
	private JComboBox c_jcb_b2 = new JComboBox();
	private JComboBox c_jcb_c1 = new JComboBox();
	private JComboBox c_jcb_c2 = new JComboBox();
	private JComboBox c_jcb_d1 = new JComboBox();
	private JComboBox c_jcb_d2 = new JComboBox();
	private JComboBox c_jcb_e1 = new JComboBox();
	private JComboBox c_jcb_e2 = new JComboBox();
	private JComboBox c_jcb_f1 = new JComboBox();
	private JComboBox c_jcb_f2 = new JComboBox();
	private JComboBox c_jcb_g1 = new JComboBox();
	private JComboBox c_jcb_g2 = new JComboBox();
	private JComboBox c_jcb_h1 = new JComboBox();
	private JComboBox c_jcb_h2 = new JComboBox();
	private JTextField c_jf4 = new JTextField(24);
	private JTextField w_jf1 = new JTextField(3);
	private ButtonGroup w_jbg = new ButtonGroup();
	private JRadioButton w_jrb1 = new JRadioButton("入口", true);
	private JRadioButton w_jrb2 = new JRadioButton("出口", false);
	private JTextField w_jf2 = new JTextField(12);
	private JComboBox w_jcb_1 = new JComboBox();
	private JComboBox w_jcb_2 = new JComboBox();
	private JTextField w_jf3 = new JTextField(9);
	private JComboBox w_jcb_3 = new JComboBox();
	private JTextField w_jf4 = new JTextField(9);
	private JCheckBox w_jcb_4 = new JCheckBox("转发至CP168控制板");
	private JTextField w_jf5 = new JTextField(9);
	private JComboBox w_jcb_5 = new JComboBox();
	private JTextField w_jf6 = new JTextField(9);
	private JComboBox w_jcb_6 = new JComboBox();
	private JComboBox w_jcb_7 = new JComboBox();
	private JComboBox w_jcb_8 = new JComboBox();
	private JCheckBox w_jcb_9 = new JCheckBox("必须人工确认才能开展");
	private JTree treeA;
	private DefaultMutableTreeNode rootA;
	private DefaultMutableTreeNode park1;
	private DefaultMutableTreeNode park1wayin1;
	private DefaultMutableTreeNode park1wayin2;
	private DefaultMutableTreeNode park1wayin3;
	private DefaultMutableTreeNode park1wayin4;
	private DefaultMutableTreeNode park1wayin5;
	private DefaultMutableTreeNode park1wayin6;
	private DefaultMutableTreeNode park1wayin7;
	private DefaultMutableTreeNode park1wayin8;
	private DefaultMutableTreeNode park1wayout1;
	private DefaultMutableTreeNode park1wayout2;
	private DefaultMutableTreeNode park1wayout3;
	private DefaultMutableTreeNode park1wayout4;
	private DefaultMutableTreeNode park1wayout5;
	private DefaultMutableTreeNode park1wayout6;
	private DefaultMutableTreeNode park1wayout7;
	private DefaultMutableTreeNode park1wayout8;
	private JTree treeB;
	private DefaultMutableTreeNode rootB;
	private DefaultMutableTreeNode computer1;
	private DefaultMutableTreeNode computer2;
	private JTree treeC;
	private DefaultMutableTreeNode rootC;
	/* private DefaultMutableTreeNode park2;
	private DefaultMutableTreeNode park2wayin1;
	private DefaultMutableTreeNode park2wayin2;
	private DefaultMutableTreeNode park2wayin3;
	private DefaultMutableTreeNode park2wayin4;
	private DefaultMutableTreeNode park2wayin5;
	private DefaultMutableTreeNode park2wayin6;
	private DefaultMutableTreeNode park2wayin7;
	private DefaultMutableTreeNode park2wayin8;
	private DefaultMutableTreeNode park2wayout1;
	private DefaultMutableTreeNode park2wayout2;
	private DefaultMutableTreeNode park2wayout3;
	private DefaultMutableTreeNode park2wayout4;
	private DefaultMutableTreeNode park2wayout5;
	private DefaultMutableTreeNode park2wayout6;
	private DefaultMutableTreeNode park2wayout7;
	private DefaultMutableTreeNode park2wayout8; */
	public ParkMessage() {
		rootA = new DefaultMutableTreeNode("停车场信息");
		park1 = new DefaultMutableTreeNode("科技小区地面停车场（测试）");
		park1wayin1 = new DefaultMutableTreeNode("科技小区东门左入口（测试）");
		park1wayin2 = new DefaultMutableTreeNode("科技小区东门右入口（测试）");
		park1wayin3 = new DefaultMutableTreeNode("科技小区西门左入口（测试）");
		park1wayin4 = new DefaultMutableTreeNode("科技小区西门右入口（测试）");
		park1wayin5 = new DefaultMutableTreeNode("科技小区南门左入口（测试）");
		park1wayin6 = new DefaultMutableTreeNode("科技小区南门右入口（测试）");
		park1wayin7 = new DefaultMutableTreeNode("科技小区北门左入口（测试）");
		park1wayin8 = new DefaultMutableTreeNode("科技小区北门右入口（测试）");
		park1wayout1 = new DefaultMutableTreeNode("科技小区东门左出口（测试）");
		park1wayout2 = new DefaultMutableTreeNode("科技小区东门右出口（测试）");
		park1wayout3 = new DefaultMutableTreeNode("科技小区西门左出口（测试）");
		park1wayout4 = new DefaultMutableTreeNode("科技小区西门右出口（测试）");
		park1wayout5 = new DefaultMutableTreeNode("科技小区南门左出口（测试）");
		park1wayout6 = new DefaultMutableTreeNode("科技小区南门右出口（测试）");
		park1wayout7 = new DefaultMutableTreeNode("科技小区北门左出口（测试）");
		park1wayout8 = new DefaultMutableTreeNode("科技小区北门右出口（测试）");
		park1.add(park1wayin1);
		park1.add(park1wayin2);
		park1.add(park1wayin3);
		park1.add(park1wayin4);
		park1.add(park1wayin5);
		park1.add(park1wayin6);
		park1.add(park1wayin7);
		park1.add(park1wayin8);
		park1.add(park1wayout1);
		park1.add(park1wayout2);
		park1.add(park1wayout3);
		park1.add(park1wayout4);
		park1.add(park1wayout5);
		park1.add(park1wayout6);
		park1.add(park1wayout7);
		park1.add(park1wayout8);
		rootA.add(park1);
		treeA = new JTree(rootA);
		
		rootC =  new DefaultMutableTreeNode("车道信息");
		rootC.add(park1wayin1);
		rootC.add(park1wayin2);
		rootC.add(park1wayin3);
		rootC.add(park1wayin4);
		treeC = new JTree(rootC);
		
		
		rootB =  new DefaultMutableTreeNode("管理电脑信息");
		computer1 = new DefaultMutableTreeNode("岗亭电脑1");
		computer2 = new DefaultMutableTreeNode("岗亭电脑2");
		computer1.add(park1wayin1);
		computer1.add(park1wayin2);
		computer1.add(park1wayout1);
		computer1.add(park1wayout2);
		computer2.add(park1wayin3);
		computer2.add(park1wayin4);
		computer2.add(park1wayout3);
		computer2.add(park1wayout4);
		rootB.add(computer1);
		rootB.add(computer2);
		treeB = new JTree(rootB);
		
		setLayout(new GridLayout(2, 3, 3, 3));
		JPanel jpa = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpa.setBorder(new TitledBorder("停车场档案"));
		jpa.add(p_zj);
		jpa.add(p_xg);
		jpa.add(p_sc);
		jpa.add(p_cc);
		jpa.add(p_fq);
		JPanel jpa_2 = new JPanel(new FlowLayout());
		jpa_2.add(new JLabel("停车场编号："));
		jpa_2.add(p_jf1);
		jpa.add(jpa_2);
		JPanel jpa_3 = new JPanel(new FlowLayout());
		jpa_3.add(new JLabel("停车场名称："));
		jpa_3.add(p_jf2);
		jpa.add(jpa_3);
		JPanel jpa_4 = new JPanel(new FlowLayout());
		jpa_4.add(new JLabel("总车位："));
		jpa_4.add(p_jf3);
		jpa.add(jpa_4);
		JPanel jpa_5 = new JPanel(new FlowLayout());
		jpa_5.add(new JLabel("临停车位："));
		jpa_5.add(p_jf4);
		jpa.add(jpa_5);
		JPanel jpa_6 = new JPanel(new FlowLayout());
		jpa_6.add(new JLabel("免费停车场（进出不收费）："));
		jpa_6.add(p_jcb1);
		jpa.add(jpa_6);
		JPanel jpa_7 = new JPanel(new FlowLayout());
		jpa_7.add(new JLabel("停车场所在层（地面/地下）："));
		jpa_7.add(p_jcb2);
		jpa.add(jpa_7);
		JPanel jpa_8 = new JPanel(new FlowLayout());
		jpa_8.add(new JLabel("备注"));
		jpa_8.add(p_jf5);
		jpa.add(jpa_8);
		add(jpa);
		JPanel jpb = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb.setBorder(new TitledBorder("管理电脑档案"));
		jpb.add(c_zj);
		jpb.add(c_xg);
		jpb.add(c_sc);
		jpb.add(c_cc);
		jpb.add(c_fq);
		JPanel jpb_2 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_2.add(new JLabel("管理电脑编号："));
		jpb_2.add(c_jf1);
		jpb.add(jpb_2);
		JPanel jpb_3 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_3.add(new JLabel("管理电脑名称："));
		jpb_3.add(c_jf2);
		jpb.add(jpb_3);
		JPanel jpb_4 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_4.add(new JLabel("管理电脑IP："));
		jpb_4.add(c_jf3);
		jpb.add(jpb_4);
		JPanel jpb_5 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_5.add(new JLabel("A入口车道编号："));
		jpb_5.add(c_jcb_a1);
		jpb_5.add(new JLabel("A出口车道编号："));
		jpb_5.add(c_jcb_a2);
		jpb.add(jpb_5);
		JPanel jpb_6 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_6.add(new JLabel("B入口车道编号："));
		jpb_6.add(c_jcb_b1);
		jpb_6.add(new JLabel("B出口车道编号："));
		jpb_6.add(c_jcb_b2);
		jpb.add(jpb_6);
		JPanel jpb_7 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_7.add(new JLabel("C入口车道编号："));
		jpb_7.add(c_jcb_c1);
		jpb_7.add(new JLabel("C出口车道编号："));
		jpb_7.add(c_jcb_c2);
		jpb.add(jpb_7);
		JPanel jpb_8 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_8.add(new JLabel("D入口车道编号："));
		jpb_8.add(c_jcb_d1);
		jpb_8.add(new JLabel("D出口车道编号："));
		jpb_8.add(c_jcb_d2);
		jpb.add(jpb_8);
		JPanel jpb_9 = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_9.add(new JLabel("E入口车道编号："));
		jpb_9.add(c_jcb_e1);
		jpb_9.add(new JLabel("E出口车道编号："));
		jpb_9.add(c_jcb_e2);
		jpb.add(jpb_9);
		JPanel jpb_a = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_a.add(new JLabel("F入口车道编号："));
		jpb_a.add(c_jcb_f1);
		jpb_a.add(new JLabel("F出口车道编号："));
		jpb_a.add(c_jcb_f2);
		jpb.add(jpb_a);
		JPanel jpb_b = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_b.add(new JLabel("G入口车道编号："));
		jpb_b.add(c_jcb_g1);
		jpb_b.add(new JLabel("G出口车道编号："));
		jpb_b.add(c_jcb_g2);
		jpb.add(jpb_b);
		JPanel jpb_c = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_c.add(new JLabel("H入口车道编号："));
		jpb_c.add(c_jcb_h1);
		jpb_c.add(new JLabel("H出口车道编号："));
		jpb_c.add(c_jcb_h2);
		jpb.add(jpb_c);
		JPanel jpb_d = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
		jpb_d.add(new JLabel("备注"));
		jpb_d.add(c_jf4);
		jpb.add(jpb_d);
		add(jpb);
        JPanel jpc = new JPanel(new FlowLayout(FlowLayout.LEFT, 3, 0));
        jpc.setBorder(new TitledBorder("进出车道档案"));
		jpc.add(w_zj);
		jpc.add(w_xg);
		jpc.add(w_sc);
		jpc.add(w_cc);
		jpc.add(w_fq);
		jpc.add(new JLabel("车道编号："));
		jpc.add(w_jf1);
		w_jbg.add(w_jrb1);
		w_jbg.add(w_jrb2);
		jpc.add(new JLabel("车道名称："));
		jpc.add(w_jf2);
		jpc.add(new JLabel("停车场出入权限："));
		jpc.add(w_jcb_1);
		jpc.add(new JLabel("控制板类型："));
		jpc.add(w_jcb_2);
		jpc.add(new JLabel("控制板IP："));
		jpc.add(w_jf3);
		jpc.add(new JLabel("摄像机类型："));
		jpc.add(w_jcb_3);
		jpc.add(new JLabel("主摄像机IP："));
		jpc.add(w_jf4);
		jpc.add(new JLabel("主摄像机转发通讯选择："));
		jpc.add(w_jcb_4);
		jpc.add(new JLabel("副摄像机IP："));
		jpc.add(w_jf5);
		jpc.add(new JLabel("满位显示屏类型"));
		jpc.add(w_jcb_5);
		jpc.add(new JLabel("满位屏IP："));
		jpc.add(w_jf6);
		jpc.add(new JLabel("发卡器类型"));
		jpc.add(w_jcb_6);
		jpc.add(new JLabel("端口："));
		jpc.add(w_jcb_7);
		jpc.add(new JLabel("通讯参数："));
		jpc.add(w_jcb_8);
		jpc.add(new JLabel("需要人工确认标志位："));
		jpc.add(w_jcb_9);
		add(jpc);
		add(new JScrollPane(treeA));
		add(new JScrollPane(treeB));
		add(new JScrollPane(treeC));
	}
	public Dimension getPreferredSize() {
		return new Dimension(1000, 730);
	}
}
